name: CI/CD Pipeline for IGO Sample QC
on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'  # Default to dev for easier testing
        type: choice
        options:
          - dev
          - production

jobs:
  deploy-to-dev:
    name: Deploy to DEV (`dlviigoapps1`)
    runs-on: self-hosted
    if: github.event.inputs.environment == 'dev'  # Only run when dev is selected
    environment: dev
    steps:
      - name: Deploy to DEV
        run: |
          echo "🚀 Deploying to DEV on dlviigoapps1..."
          cd /srv/prep/deployments/igo-sample-qc-node
          # Ensure we're on the main branch before pulling updates
          git checkout main || { echo "Failed to checkout main branch"; exit 1; }
          git pull origin main
          cd frontend/
          CI=false npm run build
          # Ensure public directory exists
          mkdir -p ../backend/public/
          cp -rT build/ ../backend/public/
          cd ..
          cp -rT backend/ /srv/www/sampleQC/
          echo "🔁 Checking if app exists in PM2..."
          if pm2 list | grep -q "sampleQC"; then
            echo "App exists, restarting..."
            pm2 restart sampleQC
          else
            echo "App doesn't exist, starting..."
            cd /srv/www/sampleQC/
            pm2 start index.js --name sampleQC
          fi
          sleep 5
          if ! pm2 show sampleQC | grep -q "status.*online"; then
            echo "❌ PM2 process 'sampleQC' failed to start!"
            pm2 logs sampleQC --lines 50
            exit 1
          fi
          echo "✅ Deployment completed successfully"

  deploy-to-prod:
    name: Deploy to PROD (`plviigoapps1`)
    runs-on: [self-hosted, prod, sample-qc-prod]
    if: github.event.inputs.environment == 'production'
    environment: production
    steps:
      - name: Deploy to PROD
        run: |
          echo "🚀 Deploying to PROD on plviigoapps1..."
          cd /srv/deployments/igo-sample-qc-node
          git pull
          # Verify that the current branch is main (ONLY DEPLOY main BRANCH TO PROD)
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [[ "$CURRENT_BRANCH" != "main" ]]; then
            echo "❌ You can only deploy the 'main' branch to PROD."
            exit 1
          fi
          cd frontend/
          CI=false npm run build
          cp -rT build/ ../backend/public/
          cd ..
          cp -rT backend/ /srv/www/sampleqc/
          chmod -R 775 /srv/www/sampleqc/public/
          pm2 restart sampleqc
          # Check if restart was successful, if not try with nvm use 16
          sleep 5
          if ! pm2 show sampleqc | grep -q "status.*online"; then
            echo "⚠️ Initial restart failed, trying with nvm use 16..."
            bash -c 'nvm use 16 && pm2 restart sampleqc'
            sleep 5
            if ! pm2 show sampleqc | grep -q "status.*online"; then
              echo "❌ PM2 process 'sampleqc' failed to start in PROD!"
              pm2 logs sampleqc --lines 50
              exit 1
            fi
          fi
          echo "✅ PROD Deployment completed successfully"
