name: CI/CD Pipeline for IGO Sample QC
on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'  # Default to dev for easier testing
        type: choice
        options:
          - dev
          - production
jobs:
  deploy-to-dev:
    name: Deploy to DEV (`dlviigoapps1`)
    runs-on: self-hosted
    if: github.event.inputs.environment == 'dev'  # Only run when dev is selected
    environment: dev
    steps:
      - name: Deploy to DEV
        run: |
          echo "🚀 Deploying to DEV on dlviigoapps1..."
          cd /srv/prep/deployments/igo-sample-qc-node
          # Ensure we're on the main branch before pulling updates
          git checkout main || { echo "Failed to checkout main branch"; exit 1; }
          git pull origin main
          cd frontend/
          CI=false npm run build
          # Ensure public directory exists
          mkdir -p ../backend/public/
          cp -rT build/ ../backend/public/
          cd ..
          cp -rT backend/ /srv/www/sampleQC/
          echo "🔁 Checking if app exists in PM2..."
          if pm2 list | grep -q "sampleQC"; then
            echo "App exists, restarting..."
            pm2 restart sampleQC
          else
            echo "App doesn't exist, starting..."
            cd /srv/www/sampleQC/
            pm2 start index.js --name sampleQC
          fi
          sleep 5
          if ! pm2 show sampleQC | grep -q "status.*online"; then
            echo "❌ PM2 process 'sampleQC' failed to start!"
            pm2 logs sampleQC --lines 50
            exit 1
          fi
          echo "✅ Deployment completed successfully"
  deploy-to-prod:
    name: Deploy to PROD (`plviigoweb1`)
    runs-on: self-hosted
    if: github.event.inputs.environment == 'production'  # Only run when production is selected
    environment: production
    steps:
      - name: Deploy to PROD
        run: |
          echo "🚀 Deploying to PROD on plviigoweb1..."
          cd /prep/deployments/igo-sample-qc-node
          # Ensure we're on the master branch before pulling updates
          git checkout master || { echo "❌ Failed to checkout master branch"; exit 1; }
          git pull origin master
          # Verify that the current branch is master
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [[ "$CURRENT_BRANCH" != "master" ]]; then
            echo "❌ You can only deploy the 'master' branch to PROD."
            exit 1
          fi
          cd frontend/
          CI=false npm run build
          # Ensure public directory exists and is copied with correct permissions
          dzdo mkdir -p ../backend/public/
          dzdo cp -rT build/ ../backend/public/
          cd ..
          dzdo cp -rT backend/ /srv/www/sampleqc/
          dzdo chmod -R 775 /srv/www/sampleqc/public/
          echo "🔁 Restarting PM2 in PROD..."
          # Use nvm to select Node.js version 16 before restarting PM2
          dzdo bash -c 'nvm use 16 || true; pm2 restart sampleqc'
          sleep 5
          if ! dzdo pm2 show sampleqc | grep -q "status.*online"; then
            echo "❌ PM2 process 'sampleqc' failed to start in PROD!"
            dzdo pm2 logs sampleqc --lines 50
            exit 1
          fi
          echo "✅ Deployment completed successfully"
